# theme.toml for the YNC Hugo theme

name = "YoungInnovations Pvt Ltd"
license = "CC BY 3.0"
licenselink = ""
description = ""
homepage = ""
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = 0.1

[author]
  name = ""
  homepage = ""

[original]
  name = ""
  homepage = "/"
  repo = ""
